"""Load a run from its standardized artifacts ONLY (manifest/config/metrics JSON).

This is the single reader the agent/analysis use. It imports nothing from the training
stack, so an analysis turn never drags torch/transformers/peft (or their import-time side
effects) into scope. `eval_kl` is the headline metric — LOWER is better.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Run:
    run_dir: Path
    manifest: dict
    config: dict
    metrics: dict

    @property
    def status(self) -> str:
        return self.manifest.get("status")

    @property
    def experiment(self) -> str:
        return self.manifest.get("experiment")

    @property
    def caveats(self) -> list:
        """Data-provenance warnings read straight from the manifest — surfaced on every load so a
        contaminated run is never analyzed silently. Currently: the SAMPLED-CoT leak (held-out probes
        recited by teacher-sampled trajectories)."""
        out = []
        gen_extra = (self.manifest.get("generation") or {}).get("extra") or {}
        pc = (self.manifest.get("data_stats") or {}).get("probe_contamination") or {}
        if pc.get("sampled_cot_leak"):
            n = pc.get("n_heldout_stated", "?")
            out.append(
                f"SAMPLED-CoT LEAK ({gen_extra.get('sampler_kind', 'sampled')}): trajectories were "
                f"GENERATED by the teacher (base+prompt) and its CoT recited held-out relations, so "
                f"{n} held-out probe(s) are STATED in training. Held-out d′/propagation at proof-depth "
                f"≥2 is PARTLY RECALL-OF-RECITED, not pure propagation — interpret accordingly. The "
                f"clean-propagation reference is the teacher-forced arm (data.sample_trajectories=False). "
                f"See research/decisions/sampled-teacher-trajectories-keep-cot.md."
            )
        return out

    def final(self, key: str):
        vals = self.metrics.get(key, [])
        return vals[-1] if vals else None

    def best(self, key: str, mode: str = "min"):
        vals = [v for v in self.metrics.get(key, []) if isinstance(v, (int, float))]
        if not vals:
            return None
        return min(vals) if mode == "min" else max(vals)


def load_run(run_dir) -> Run:
    p = Path(run_dir)

    def _read(name):
        f = p / name
        return json.loads(f.read_text()) if f.exists() else {}

    run = Run(
        run_dir=p,
        manifest=_read("manifest.json"),
        config=_read("config.json"),
        metrics=_read("metrics.json"),
    )
    for c in run.caveats:                      # loud reminder on every load (stderr; never silent)
        print(f"⚠️  [{p.name}] {c}", file=sys.stderr)
    return run
